# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-json
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: [--line-length=120]
        files: \.py$

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
    -   id: clang-format
        files: \.(h|cpp)$
