name: build-image

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-image.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-image.yml'

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ github.ref_name }}

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ github.ref_name }}

    - name: Push to latest for main
      if: github.ref_name == 'main'
      run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ github.ref_name }} ${{ secrets.DOCKERHUB_USERNAME }}/rustle && docker push ${{ secrets.DOCKERHUB_USERNAME }}/rustle
