name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'detectors/**'
      - 'utils/**'
  pull_request:
    paths:
      - 'detectors/**'
      - 'utils/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" 15 all

    - name: Lint
      run: make lint

    - name: Something needs to be fixed?
      run: |
        if test -f "clang-tidy-fixes.yaml"; then
          exit 1
        fi

  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Build the docker image
  #     run: docker build --build-arg UID=`id -u` --build-arg GID=`id -g` -t rustle .

  #   - name: Run the Docker image for unit test
  #     run: docker run -v `pwd`:/rustle -w /rustle rustle scripts/unit_test.sh
