name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'detectors/**'
      - 'utils/**'
      - 'Makefile'
      - 'rustle'
      - 'rust-toolchain.toml'
      - '.clang-tidy'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" 15 all

    - name: Lint
      run: make lint

    - id: check_file
      uses: andstor/file-existence-action@v2
      with:
        files: "clang-tidy-fixes.yaml"

    - name: Upload fix file when something needs to be fixed?
      uses: actions/upload-artifact@v3
      if: steps.check_file.outputs.files_exists == 'true'
      with:
        name: clang-tidy-fixes
        path: clang-tidy-fixes.yaml

    - name: Exit when something needs to be fixed?
      if: steps.check_file.outputs.files_exists == 'true'
      run: exit 1

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the docker image
      run: docker build --build-arg UID=`id -u` --build-arg GID=`id -g` -t rustle .

    - name: Run the Docker image for unit test
      run: docker run -v `pwd`:/rustle -w /rustle rustle scripts/unit_test.sh
