name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'detectors/'
      - 'utils/'
  pull_request:
    paths:
      - 'detectors/'
      - 'utils/'

jobs:

  build-and-test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rustle
    - name: Run the Docker image
      run: docker run -v `pwd`:/home/rustle/rustle -u rustle -w /home/rustle/rustle ${{ secrets.DOCKERHUB_USERNAME }}/rustle bash -c \
        "scripts/unit_test.sh"
