name: unit-test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'detectors/**'
      - 'utils/**'
  pull_request:
    paths:
      - 'detectors/**'
      - 'utils/**'

jobs:

  pull-image-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: docker-tag
      uses: yuya-takeyama/docker-tag-from-github-ref-action@v1.0.0

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Pull the Docker image
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ steps.docker-tag.outputs.tag }}
      
    - name: Build and push the image on failures
      if: failure()
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ steps.docker-tag.outputs.tag }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ steps.docker-tag.outputs.tag }}

    - name: Run the Docker image to test
      if: always()
      run: docker run -u rustle -w /home/rustle ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ steps.docker-tag.outputs.tag }} bash -c \
        "git clone -b ${{ github.ref_name }} https://github.com/blocksecteam/rustle; cd rustle; scripts/unit_test.sh"
