name: unit-test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'detectors/'
      - 'utils/'
  pull_request:
    paths:
      - 'detectors/'
      - 'utils/'

jobs:

  pull-image-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Pull the Docker image
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ github.ref }}

    - name: Run the Docker image to test
      run: docker run -u rustle -w /home/rustle ${{ secrets.DOCKERHUB_USERNAME }}/rustle:${{ github.ref }} bash -c \
        "git clone https://github.com/blocksecteam/rustle; cd rustle; scripts/unit_test.sh"
