name: unit-test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'detectors/**'
      - 'utils/**'
  pull_request:
    paths:
      - 'detectors/**'
      - 'utils/**'

jobs:

  pull-image-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the docker image
      run: docker build --build-arg UID=`id -u` --build-arg GID=`id -g` -t rustle .

    - name: Run the Docker image for unit test
      run: docker run -v `pwd`:/rustle -w /rustle rustle scripts/unit_test.sh
